<Project>
  <PropertyGroup>
    <!-- Code Analysis Settings -->
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningLevel>5</WarningLevel>
  </PropertyGroup>
</Project>

