version: '3.8'

services:
  doctorloan-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./wwwroot:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Production